<?php
// Placeholder for selected pet data - this will be set via JavaScript
$selected_pet = [
    'name' => 'Your Pet',
    'photo' => '🐾',
    'breed' => 'Unknown',
    'age' => 0,
    'weight' => 0,
    'ideal_weight' => 0,
    'activity_level' => 'Unknown',
];

// Sample diet plan - this will be generated by PHP backend later
$sampleDietPlan = [
    'dailyCalories' => 1100,
    'mealsPerDay' => 3,
    'recommendations' => [
        [
            'time' => '7:00 AM',
            'meal' => 'Breakfast',
            'food' => 'High-Quality Dry Kibble',
            'portion' => '1 cup (85g)',
            'calories' => 340,
            'tips' => 'Mix with a little warm water for better digestion'
        ],
        [
            'time' => '1:00 PM',
            'meal' => 'Lunch',
            'food' => 'Lean Protein + Vegetables',
            'portion' => '1/2 cup (60g)',
            'calories' => 220,
            'tips' => 'Great time for training treats!'
        ],
        [
            'time' => '6:00 PM',
            'meal' => 'Dinner',
            'food' => 'Premium Wet Food',
            'portion' => '1 can (150g)',
            'calories' => 380,
            'tips' => 'Let food reach room temperature before serving'
        ],
        [
            'time' => 'Throughout day',
            'meal' => 'Healthy Treats',
            'food' => 'Training Treats & Vegetables',
            'portion' => '1/4 cup (20g)',
            'calories' => 160,
            'tips' => 'Use for training and bonding time'
        ]
    ],
    'nutritionBreakdown' => [
        'protein' => '28%',
        'fat' => '15%',
        'fiber' => '4%',
        'moisture' => '12%'
    ]
];

?>

<div class="space-y-6">
    <div class="bg-white shadow-sm border-b">
        <div class="px-6 py-6">
            <div class="flex items-center justify-between">
                <div>
                    <h2 class="text-3xl font-bold text-gray-900">Nutrition Plans</h2>
                    <p class="text-gray-600 mt-1" id="nutrition-subtitle">Customized feeding recommendations for your pets</p>
                </div>
                <div class="flex items-center space-x-4">
                    <button class="relative p-3 text-gray-600 hover:text-gray-900 bg-gray-100 rounded-full">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-bell w-5 h-5"><path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"/><path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"/></svg>
                        <span class="absolute -top-1 -right-1 w-5 h-5 bg-red-500 text-white text-xs rounded-full flex items-center justify-center">2</span>
                    </button>
                    <div class="text-right">
                        <p class="text-sm font-medium text-gray-900">Welcome back!</p>
                        <p class="text-xs text-gray-500"><?php echo date('M d, Y'); ?></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="px-6">
        <div id="nutrition-content">
            <div class="text-center py-16" id="select-pet-message">
                <div class="bg-white rounded-xl shadow-lg p-12">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-heart w-16 h-16 text-gray-400 mx-auto mb-4"><path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"/></svg>
                    <h3 class="text-2xl font-semibold text-gray-900 mb-3">Choose Your Pet</h3>
                    <p class="text-gray-600 mb-6">Select one of your pets to view their personalized nutrition plan</p>
                    <div class="grid grid-cols-1 md:grid-cols-3 gap-4 max-w-2xl mx-auto" id="pet-selection-grid">
                        <!-- Pet selection buttons will be loaded here by JavaScript -->
                    </div>
                </div>
            </div>

            <div class="space-y-6 hidden" id="selected-pet-nutrition-details">
                <!-- Pet Header -->
                <div class="bg-gradient-to-r from-green-400 to-blue-500 rounded-xl text-white p-6">
                    <div class="flex items-center space-x-4">
                        <span class="text-5xl" id="nutrition-pet-photo"></span>
                        <div class="flex-1">
                            <h3 class="text-3xl font-bold" id="nutrition-pet-name"></h3>
                            <p class="text-green-100 mt-1" id="nutrition-pet-details"></p>
                        </div>
                        <button class="px-6 py-3 bg-white text-blue-600 rounded-lg hover:bg-gray-100 transition-colors font-semibold">
                            Update Plan
                        </button>
                    </div>
                </div>

                <!-- Nutrition Overview -->
                <div class="grid grid-cols-1 md:grid-cols-4 gap-6">
                    <div class="bg-white rounded-xl shadow-lg p-6 text-center">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-target w-8 h-8 text-blue-600 mx-auto mb-3"><circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/></svg>
                        <p class="text-gray-600 text-sm font-medium">Daily Calories</p>
                        <p class="text-2xl font-bold text-gray-900" id="daily-calories"><?php echo $sampleDietPlan['dailyCalories']; ?></p>
                        <p class="text-xs text-gray-500 mt-1">Perfect for <span id="daily-calories-pet-name"></span></p>
                    </div>
                    <div class="bg-white rounded-xl shadow-lg p-6 text-center">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-clock w-8 h-8 text-green-600 mx-auto mb-3"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>
                        <p class="text-gray-600 text-sm font-medium">Meals per Day</p>
                        <p class="text-2xl font-bold text-gray-900" id="meals-per-day"><?php echo $sampleDietPlan['mealsPerDay']; ?></p>
                        <p class="text-xs text-gray-500 mt-1">Optimal timing</p>
                    </div>
                    <div class="bg-white rounded-xl shadow-lg p-6 text-center">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-scale w-8 h-8 text-purple-600 mx-auto mb-3"><path d="m16 16 3-3m-3 3 3 3m-3-3H4m12 0a7 7 0 1 1 0-14h5v4"/></svg>
                        <p class="text-gray-600 text-sm font-medium">Target Weight</p>
                        <p class="text-2xl font-bold text-gray-900" id="target-weight"></p>
                        <p class="text-xs text-gray-500 mt-1">Healthy goal</p>
                    </div>
                    <div class="bg-white rounded-xl shadow-lg p-6 text-center">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-activity w-8 h-8 text-yellow-600 mx-auto mb-3"><path d="M22 12h-4l-3 9L9 3l-3 9H2"/></svg>
                        <p class="text-gray-600 text-sm font-medium">Activity Level</p>
                        <p class="text-2xl font-bold text-gray-900" id="activity-level"></p>
                        <p class="text-xs text-gray-500 mt-1">Energy needs</p>
                    </div>
                </div>

                <!-- Daily Feeding Schedule -->
                <div class="bg-white rounded-xl shadow-lg">
                    <div class="px-6 py-4 border-b border-gray-100">
                        <h3 class="text-xl font-semibold text-gray-900">Daily Feeding Schedule</h3>
                        <p class="text-gray-600 text-sm">Customized meal plan for <span id="feeding-schedule-pet-name"></span></p>
                    </div>
                    <div class="p-6">
                        <div class="space-y-4" id="feeding-schedule-list">
                            <?php foreach ($sampleDietPlan['recommendations'] as $meal): ?>
                                <div class="bg-gray-50 rounded-lg p-4 border-l-4 border-blue-500">
                                    <div class="flex items-start justify-between">
                                        <div class="flex-1">
                                            <div class="flex items-center space-x-3 mb-2">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-clock w-5 h-5 text-blue-600"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>
                                                <span class="font-semibold text-gray-900"><?php echo $meal['time']; ?></span>
                                                <span class="text-sm bg-blue-100 text-blue-800 px-2 py-1 rounded-full"><?php echo $meal['meal']; ?></span>
                                            </div>
                                            <h4 class="font-medium text-gray-900 mb-1"><?php echo $meal['food']; ?></h4>
                                            <p class="text-sm text-gray-600 mb-2"><?php echo $meal['tips']; ?></p>
                                        </div>
                                        <div class="text-right ml-4">
                                            <p class="font-semibold text-lg text-gray-900"><?php echo $meal['portion']; ?></p>
                                            <p class="text-sm text-gray-600"><?php echo $meal['calories']; ?> calories</p>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>

                <!-- Nutrition Facts -->
                <div class="bg-white rounded-xl shadow-lg">
                    <div class="px-6 py-4 border-b border-gray-100">
                        <h3 class="text-xl font-semibold text-gray-900">Nutrition Breakdown</h3>
                        <p class="text-gray-600 text-sm">Balanced nutrients for optimal health</p>
                    </div>
                    <div class="p-6">
                        <div class="grid grid-cols-2 md:grid-cols-4 gap-6">
                            <?php foreach ($sampleDietPlan['nutritionBreakdown'] as $nutrient => $value): ?>
                                <div class="text-center p-4 bg-gray-50 rounded-lg">
                                    <p class="text-sm text-gray-600 font-medium capitalize mb-2"><?php echo $nutrient; ?></p>
                                    <p class="text-3xl font-bold text-gray-900"><?php echo $value; ?></p>
                                    <div class="mt-2 w-full bg-gray-200 rounded-full h-2">
                                        <div 
                                            class="bg-blue-600 h-2 rounded-full" 
                                            style="width: <?php echo $value; ?>"
                                        ></div>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Add Pet Modal (hidden by default) -->
<div id="add-pet-modal" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 hidden">
    <div class="bg-white rounded-xl shadow-2xl max-w-2xl w-full mx-4 max-h-screen overflow-y-auto">
        <div class="px-6 py-4 border-b border-gray-100">
            <div class="flex items-center justify-between">
                <h3 class="text-xl font-semibold text-gray-900">Add New Family Member</h3>
                <button id="close-add-pet-modal" class="text-gray-400 hover:text-gray-600">
                    ✕
                </button>
            </div>
            <p class="text-gray-600 text-sm mt-1">Tell us about your new pet so we can create the perfect nutrition plan</p>
        </div>
        
        <form id="add-pet-form" class="p-6">
            <div class="space-y-6">
                <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div>
                        <label for="pet-name" class="block text-sm font-medium text-gray-700 mb-2">Pet's Name *</label>
                        <input
                            type="text"
                            id="pet-name"
                            name="name"
                            class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                            placeholder="What's your pet's name?"
                            required
                        >
                    </div>
                    
                    <div>
                        <label for="pet-species" class="block text-sm font-medium text-gray-700 mb-2">Species *</label>
                        <select id="pet-species" name="species" class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent" required>
                            <option value="">Choose your pet type</option>
                            <option value="Dog">Dog 🐕</option>
                            <option value="Cat">Cat 🐱</option>
                            <option value="Rabbit">Rabbit 🐰</option>
                            <option value="Bird">Bird 🐦</option>
                        </select>
                    </div>
                    
                    <div>
                        <label for="pet-breed" class="block text-sm font-medium text-gray-700 mb-2">Breed</label>
                        <input
                            type="text"
                            id="pet-breed"
                            name="breed"
                            class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                            placeholder="e.g., Golden Retriever, Persian Cat"
                        >
                    </div>
                    
                    <div>
                        <label for="pet-age" class="block text-sm font-medium text-gray-700 mb-2">Age *</label>
                        <input
                            type="number"
                            id="pet-age"
                            name="age"
                            class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                            placeholder="Age in years"
                            required
                        >
                    </div>
                    
                    <div>
                        <label for="pet-weight" class="block text-sm font-medium text-gray-700 mb-2">Current Weight (kg) *</label>
                        <input
                            type="number"
                            step="0.1"
                            id="pet-weight"
                            name="weight"
                            class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                            placeholder="Current weight"
                            required
                        >
                    </div>
                    
                    <div>
                        <label for="pet-activity" class="block text-sm font-medium text-gray-700 mb-2">Activity Level *</label>
                        <select id="pet-activity" name="activity_level" class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent" required>
                            <option value="">How active is your pet?</option>
                            <option value="Low">Low - Mostly indoors, minimal exercise</option>
                            <option value="Medium">Medium - Regular walks, some playtime</option>
                            <option value="High">High - Very active, lots of exercise</option>
                        </select>
                    </div>
                    <div>
                        <label for="pet-photo" class="block text-sm font-medium text-gray-700 mb-2">Pet Photo (Emoji)</label>
                        <input
                            type="text"
                            id="pet-photo"
                            name="photo"
                            class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                            placeholder="e.g., 🐕, 🐱, 🐰"
                        >
                    </div>
                </div>
                
                <div>
                    <label for="pet-personality" class="block text-sm font-medium text-gray-700 mb-2">Personality & Notes</label>
                    <textarea
                        id="pet-personality"
                        name="personality"
                        class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                        rows="3"
                        placeholder="Tell us about your pet's personality, any health conditions, or special needs..."
                    ></textarea>
                </div>
            </div>
        </form>
        
        <div class="px-6 py-4 border-t border-gray-100 bg-gray-50 flex justify-end space-x-3">
            <button
                id="cancel-add-pet"
                type="button"
                class="px-6 py-3 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
            >
                Cancel
            </button>
            <button
                id="submit-add-pet"
                type="submit"
                form="add-pet-form"
                class="px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
            >
                Add My Pet
            </button>
        </div>
    </div>
</div>